# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: sayan0361
# "service" is the name of this project. This will also be added to your AWS resource names.
service: user-service

provider:
  name: aws
  runtime: nodejs20.x
  versionFunctions: false
  stage: "dev"
  region: ap-south-1
  httpApi:
    cors: true
    throttling:
      burstLimit: 10
      rateLimit: 3

  environment:
    AWS_REGION: ap-south-1

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sns:Publish
          Resource: "*"
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

# Auth api endpoints
functions:
  signup:
    handler: app/handler.Signup
    events:
      - httpApi:
          path: /signup
          method: post
  login:
    handler: app/handler.Login
    events:
      - httpApi:
          path: /login
          method: post
  verify:
    handler: app/handler.Verify
    events:
      - httpApi:
          path: /verify
          method: get
      - httpApi:
          path: /verify
          method: post
  profile:
    handler: app/handler.Profile
    events:
      - httpApi:
          path: /user
          method: post
      - httpApi:
          path: /user
          method: put
      - httpApi:
          path: /user
          method: get
  cart:
    handler: app/handler.Cart
    events:
      - httpApi:
          path: /cart
          method: post
      - httpApi:
          path: /cart
          method: put
      - httpApi:
          path: /cart
          method: get
  account:
    handler: app/handler.Account
    events:
      - httpApi:
          path: /account
          method: post
      - httpApi:
          path: /account
          method: put
      - httpApi:
          path: /account
          method: get

plugins:
  - serverless-offline

build:
  esbuild: true