CREATE TABLE users (
    user_id BIGSERIAL PRIMARY KEY,
    phone VARCHAR(15) NOT NULL UNIQUE,
    email VARCHAR(255) UNIQUE,
    password VARCHAR NOT NULL,
    salt VARCHAR NOT NULL,
    user_type VARCHAR NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);